### ISSUE TITLE
关闭后第二次打开又会变成获取定位

### ISSUE THREAD

**Issue by PandaFang** [yuruizhe/CityPicker#2]
定位成功后第一次打开显示的是定位城市关闭后第二次打开又会变成获取定位
所以每次打开前需要  readme 中的 step3
`//使用百度定位
CityPicker.setGpsCityByBaidu("南京市","315");

//高德定位
CityPicker.setGpsCityByAMap("南京市","025");`

这是bug 还是 feature ？

**Comment by yuruizhe** [comment]
设计如此
具体定位需要自己接入百度或高德，在定位回调中调用step3
